import { PlaceTypes } from './types';
export const dinnerFancy: PlaceTypes[] = [
  {
    title: 'Fox & Pearl',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.foxandpearlkc.com/',
    address: '2143 Summit St. Kansas City, MO 64108',
  },
  {
    title: 'Antons',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://antonskc.com/',
    address: '1610 Main St. Kansas City, MO 64108',
  },
  {
    title: 'Antler Room',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.theantlerroomkc.com/',
    address: '2506 Holmes St. Kansas City, MO 64108',
  },
  {
    title: 'Corvino',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 4,
    link: 'https://corvino.com/',
    address: '1830 Walnut St. Kansas City, MO 64108',
  },
  {
    title: 'La Bodega',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://labodegakc.com/',
    address: '703 Southwest Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Ragazza',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://ragazzakc.com/',
    address: '4301 Main St. Kansas City, MO 64111',
  },
  {
    title: 'Garozzos',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.garozzos.com/',
    address: '526 Harrison St. Kansas City, MO 64106',
  },
  {
    title: 'Town Company',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://thetowncompany.com/',
    address: '1228 Baltimore Avenue, Kansas City, MO 64105',
  },
  {
    title: 'Extra Virgin',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.extravirginkc.com/',
    address: '1900 Main St. Kansas City, MO 64108',
  },
  {
    title: 'Farina',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://farinakc.com/',
    address: '19 W 19th St. Kansas City, MO 64108',
  },
  {
    title: 'Le Fou Frog',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.lefoufrog.com/',
    address: '400 E 5th St. Kansas City, MO 64106',
  },
  {
    title: 'Voltaire',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'http://voltairekc.com/',
    address: '1617 Genessee Kansas City, MO 64102',
  },
  {
    title: 'Savoy',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.thesavoykc.com/',
    address: '219 W 9th St. Kansas City, MO 64105',
  },
  {
    title: 'Rye',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'http://ryekc.com/plaza/',
    address: '4646 Mill Creek Parkway, Kansas City, MO 64112',
  },
  {
    title: 'Lidias',
    content:
      'Good, but too expensive for what you get. Ragazza or Garozzos will get you better italian food with a cheaper price tag.',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://lidias-kc.com/',
    address: '101 W 22nd St. Kansas City, MO 64108',
  },
];

export const dinnerCas: PlaceTypes[] = [
  {
    title: 'Baramee Thai',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.barameethaibistro.com/',
    address: '1810 Baltimore Avenue Kansas City, MO 64108',
  },
  {
    title: 'Kobi Q',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.kobi-q.com/',
    address: '1531 Grand Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Port Fonda',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://portfonda.com/',
    address: '4141 Pennsylvania, Kansas City, MO 64111',
  },
  {
    title: 'Westside Local',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://thewestsidelocal.com/',
    address: '1663 Summit St, Kansas City, MO 64108',
  },
  {
    title: 'Pigwich',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 1,
    link: 'https://www.pigwich.com/',
    address: '20 E 5th St, Kansas City, MO 64106',
  },
  {
    title: 'Il Lazzarone',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://illazzarone.org/',
    address: '412 Delaware St. Kansas City, MO 64105',
  },
  {
    title: 'Ravenous',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    address: '1707 Locust St. Kansas City, MO 64108',
  },
  {
    title: 'Columbus Park Ramen Shop',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://columbusparkramenshop.com/',
    address: '549 Gillis St. Kansas City, MO 64106',
  },
  {
    title: 'Lulus',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.lulusnoodles.com/',
    address: '2030 Central St. Kansas City, MO',
  },
  {
    title: 'Los Tules',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 1,
    link: 'https://los-tuleskc.com/',
    address: '1656 Broadway Blvd, Kansas City, MO 64108',
  },
  {
    title: 'BRGR',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.brgrkitchen.com/',
    address: '11 E. 14th St. Kansas City, MO 64105',
  },
  {
    title: 'KC Taco Company',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'http://www.kctacocompany.com/',
    address: '520 Walnut St. Kansas City, MO 64106',
  },
  {
    title: 'Brown & Loe',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.brownandloe.com/',
    address: '429 Walnut St. Kansas City, MO 64106',
  },
  {
    title: 'Parlor',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.parlorkcmo.com/',
    address: '1707 Locust St. Kansas City, MO 64108',
  },
  {
    title: 'Tribe Street Kitchen',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.tribekc.com/',
    address: '316 Delaware St. Kansas City, MO 64105',
  },
  {
    title: 'Cluster Truck',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://kansas-city.clustertruck.com/',
  },
  {
    title: "Gui Fieri's Taco Joint",
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
  },
  {
    title: 'Mickeys Hideaway',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://mickeyskc.com/',
    address: '4057 Pennsylvania Kansas City, MO 64111',
  },
  {
    title: 'Town Topic',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 1,
    link: 'http://www.towntopic.com/',
    address: '2021 Broadway St. Kansas City, MO 64108',
  },
];

export const breakfast: PlaceTypes[] = [
  {
    title: 'Happy Gillis',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://happygillis.com/',
    address: '549 Gillis St. Kansas City, MO 64106',
  },
  {
    title: 'Mildreds',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.mildredskc.com/',
    address: '1901 Wyandotte St. Kansas City, Missouri, 64108',
  },
  {
    title: 'Banksia',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://banksiabakehouse.com/',
    address: '105 W 9th St, Kansas City, 64105',
  },
  {
    title: 'Room 39',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'http://www.rm39.com/',
    address: '1719 W 39th Street, KCMO, 64111',
  },
  {
    title: 'Farmhouse',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.eatatthefarmhouse.com/',
    address: '300 Delaware St. Kansas City, MO 64105',
  },
  {
    title: 'Succotash',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'http://www.succotashkcmo.com/',
    address: '2601 Holmes Kansas City, Mo 64108',
  },
  {
    title: 'Opera House Coffee and Food Emporium',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 1,
    link: 'https://operahousekc.com/',
    address: '500 Walnut St. Kansas City, MO 64106',
  },
  {
    title: 'Billies Grocery',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.billiesgrocery.com/',
    address: '3216 Gillham Plaza, Suite 100, Kansas City, MO 64109',
  },
  {
    title: 'City Diner',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 1,
    link: 'https://www.citydinerkcmo.com/',
    address: '301 Grand Blvd. Kansas City, MO 64106',
  },
  {
    title: 'Eggtc.',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://eggtckc.com/',
    address: '5107 Main St. Kansas City, MO 64112',
  },
];

export const cocktails: PlaceTypes[] = [
  {
    title: 'Crossroads Hotel',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://crossroadshotelkc.com/',
    address: '2101 Central St. Kansas City, MO 64108',
  },
  {
    title: 'The Campground',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://thecampgroundkc.com/',
    address: '1531 Gennessee St. Kansas City, MO 64102',
  },
  {
    title: 'Panthers Place',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.yelp.com/biz/panther-s-place-kansas-city',
    address: '1000 W 25th St. Kansas City, MO 64108',
  },
  {
    title: 'SwordFish Toms',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.yelp.com/biz/swordfish-toms-kansas-city',
    address: '210 W 19th Ter. Kansas City, MO 64108',
  },
  {
    title: 'Hey! Hey! Club',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.jriegerco.com/heyheyclub',
    address: '2700 Guinotte Ave. Kansas City, MO 64120',
  },
  {
    title: 'Hotel Kansas City Lobby Bar',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.hotelkc.com/dine/lobby-bar',
    address: '1228 Baltimore Ave. Kansas City, MO 64105',
  },
  {
    title: 'Westport Cafe',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://westportcafeandbar.com/',
    address: '419 Westport Road, Kansas City, MO 64111',
  },
  {
    title: 'Drastic Measures',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://www.drasticbar.com/',
    address: ' 5817 Nieman Road, Shawnee KS, 66203',
  },
  {
    title: 'Toms Town',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.toms-town.com/',
    address: '1701 Main St. Kansas City, MO 64108',
  },
  {
    title: 'Afterword',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.afterwordkc.com/',
    address: '1834 Grand Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Green lady Lounge',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://greenladylounge.com/',
    address: '1809 Grand Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Monarch Bar',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.themonarchbar.com/',
    address: '4808 Roanoke Parkway, Kansas City, MO 64112',
  },
  {
    title: 'Mercury Room',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 4,
    link: ' https://themercuryroom.com/',
    address: '1800 Walnut Street, 14th Floor, Kansas City, MO 64108',
  },
  {
    title: 'Julep',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.julepkc.com/',
    address: '4141 Pennsylvania Ave, Suite 104, Kansas City, MO 64111',
  },
  {
    title: 'Lifted Spirits',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.liftedspiritskc.com/',
    address: '1734 Cherry St. Kansas City, MO 64108',
  },
  {
    title: 'P.S.',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 3,
    link: 'https://www.ps1931.com/',
    address: '106 W 12th St. Kansas City, MO 64105',
  },
  {
    title: 'SoT',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 3,
    link: 'https://www.sotkc.com/',
    address: '1521 Grand Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Kill Devil Club',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://www.powerandlightdistrict.com/eat-and-drink/kill-devil-club',
    address: '31 E 14th St. Kansas City, MO 64105',
  },
  {
    title: 'Harpos',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://www.harposkc.com/',
    address: '4109 Pennsylvania Avenue, Kansas City, MO 64111',
  },
  {
    title: 'No Other Pub',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 2,
    link: 'https://powerandlightdistrict.com/eat-and-drink/no-other-pub',
    address: '1370 Grand Blvd. Kansas City, MO 64106',
  },
];

export const beerAndCasual: PlaceTypes[] = [
  {
    title: 'Boulevard Brewing',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.boulevard.com/',
    address: '2501 Southwest Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Alma Mader Brewing',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.almamaderbrewing.com/',
    address: '2635 Southwest Boulevard Kansas City, MO, 64108',
  },
  {
    title: 'Casual Animal Brewing',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.casualanimalbrewing.com/',
    address: '1725 McGee St. Kansas City, MO 64108',
  },
  {
    title: 'Double Shift Brewing',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://doubleshiftbrewing.com/',
    address: '412 E 18th St. Kansas City, MO 64108',
  },
  {
    title: 'KC Bier Co',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://kcbier.com/',
    address: '310 W 79th St. Kansas City, MO 64114',
  },
  {
    title: 'The Ship',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 1,
    link: 'https://www.theshipkc.com/',
    address: '1217 Union Ave. Kansas City, MO 64101',
  },
  {
    title: 'City Barrel',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.yelp.com/biz/city-barrel-brewing-co-kansas-city',
    address: '1740 Holmes, Kansas City, MO 64108',
  },
  {
    title: 'Blue Line',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 1,
    link: 'https://www.thebluelinekc.com/',
    address: '529 Walnut St. Kansas City, Missouri 64106',
  },
];

export const wine: PlaceTypes[] = [
  {
    title: 'ÇaVa',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.cavakc.com/',
    address: '4149 Pennsylvania St. Kansas City, MO 64111',
  },
  {
    title: 'Westport Cafe',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://westportcafeandbar.com/',
    address: '419 Westport Road, Kansas City, MO 64111',
  },
  {
    title: 'The Campground',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 3,
    link: 'https://thecampgroundkc.com/',
    address: '1531 Gennessee St. Kansas City, MO 64102',
  },
  {
    title: 'Amigoni Urban Winery',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.amigoni.com/',
    address: '1505 Genessee Suite 100, Kansas City, MO 64102',
  },
  {
    title: 'KC Wineworks',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://kcwineworks.com/',
    address: '1829 McGee St. Kansas City, MO 64108',
  },
  {
    title: 'Tannin',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.tanninwinebar.com/',
    address: '1526 Walnut St. Kansas City, MO 64108',
  },
  {
    title: 'KC Wine Co',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.kcwineco.com/',
    address: '13875 S. Gardner Rd. Olathe, KS 66061',
  },
];

export const caffeine: PlaceTypes[] = [
  {
    title: 'Oddly Correct',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://oddlycorrect.com/',
    address: '3940 Main St. Kansas City, MO 64111',
  },
  {
    title: 'Cafe Ca Phe',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.cafecaphe.com/',
  },
  {
    title: 'Second Best',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.secondbestcoffee.com/',
    address: '328 W 85th St. Kansas City, MO 64114',
  },
  {
    title: 'Monarch',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.monarchcoffeekc.com/',
    address: '3550 Broadway, Kansas City, MO 64111',
  },
  {
    title: 'PTs',
    content: 'description of why this place got its placement',
    rating: 'do',
    dollarSigns: 2,
    link: 'https://www.ptscoffee.com/',
    address: '310 Southwest Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Thou Mayest',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 1,
    link: 'https://thoumayest.com/',
    address: '412 Delaware St. Kansas City, MO 64105',
  },
  {
    title: 'The Roasterie',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 1,
    link: 'https://theroasterie.com/',
    address: '1204 W 27th St. Kansas City MO 64108',
  },
  {
    title: 'Messenger',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://messengercoffee.co/',
    address: '1624 Grand Blvd. Kansas City, MO 64108',
  },
  {
    title: 'Vested',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 2,
    link: 'https://www.vested.coffee/',
    address: '310 W 8th St. Kansas City, Missouri 64105',
  },
  {
    title: 'Spokes',
    content: 'description of why this place got its placement',
    rating: 'average',
    dollarSigns: 1,
    link: 'https://www.spokeskc.com/',
    address: '1200 Washington St. Suite B. Kansas City, MO 64105',
  },
  {
    title: 'Crows',
    content: 'description of why this place got its placement',
    rating: 'dont',
    dollarSigns: 1,
    link: 'https://crowscoffee.com/',
    address: '304 E. 51st St. Kansas City, Missouri 64112',
  },
];
